export type Presigned = {url: string; method: 'PUT'; headers: Record<string, string>; expiresAt: number};
export type StoredObject = {body: ReadableStream<Uint8Array>; size?: number; contentType?: string};
export type PresignOptions = {mime: string; size: number; expiresSec?: number};
export type ListedObject = {key: string; modified: Date; size?: number};
export type ListOptions = {limit?: number; after?: string};
export interface Storage {
  driver: 's3' | 'local';
  /** A short-lived URL the browser can PUT exactly one object of the declared type and size to. */
  presignUpload(key: string, options: PresignOptions): Promise<Presigned>;
  /** Resolves to null when the object does not exist. */
  getObject(key: string): Promise<StoredObject | null>;
  putObject(key: string, body: Uint8Array, contentType: string): Promise<void>;
  deleteObjects(keys: string[]): Promise<void>;
  /** Removes every object whose key starts with `prefix` (a directory-like prefix ending in "/"). */
  deletePrefix(prefix: string): Promise<void>;
  exists(key: string): Promise<boolean>;
  /**
   * Objects whose key starts with `prefix` (ending in "/"), in ascending key order, at most `limit` (default 1000).
   * `after` continues a listing: only keys greater than it are returned.
   */
  list(prefix: string, options?: ListOptions): Promise<ListedObject[]>;
  /** Stores a file from disk without reading it into memory (database dumps). The object is private: no cache headers. */
  putFile(key: string, path: string, contentType: string): Promise<void>;
}
export const UPLOAD_TTL_SEC = 300;
const KEY = /^[A-Za-z0-9_-]+(\/[A-Za-z0-9_-][A-Za-z0-9_.-]*)*\/?$/;
/** Keys are generated by the server, but they also arrive in URLs; anything unusual is refused before it reaches a driver. */
export function assertKey(key: string) {
  if (key.length > 300 || !KEY.test(key) || key.includes('..')) throw new Error('INVALID_STORAGE_KEY');
  return key;
}
/** Buffers a stream, giving up as soon as it grows past `maxBytes`. Resolves to null when the limit is exceeded. */
export async function readStream(stream: ReadableStream<Uint8Array>, maxBytes: number) {
  const reader = stream.getReader();
  const chunks: Uint8Array[] = [];
  let total = 0;
  for (;;) {
    const {done, value} = await reader.read();
    if (done) break;
    total += value.byteLength;
    if (total > maxBytes) {await reader.cancel().catch(() => {}); return null;}
    chunks.push(value);
  }
  return Buffer.concat(chunks, total);
}
