import {readFileSync,writeFileSync} from 'node:fs';
const rows=[
['photoHeroAlt','A couple dancing swing in a warmly lit hall','Пара танцует свинг в зале с тёплым освещением','Una pareja baila swing en un salón de luz cálida'],
['photoClassesAlt','Swing dancers practising together in a bright hall','Танцоры практикуют свинг вместе в светлом зале','Bailarines practican swing juntos en un salón luminoso'],
['photoLessonAlt','A teacher demonstrates a solo step to a group of dancers','Преподаватель показывает сольный шаг группе танцоров','Una profesora muestra un paso individual a un grupo de bailarines'],
['photoParkAlt','A couple dances in a park with musicians in the background','Пара танцует в парке, на заднем плане музыканты','Una pareja baila en un parque con músicos al fondo'],
['photoSocialAlt','A couple dances beside a jazz band in a club','Пара танцует рядом с джазовым ансамблем в клубе','Una pareja baila junto a una banda de jazz en un club'],
['searchOptions','Search: {name}','Поиск: {name}','Buscar: {name}'],
['selectVisible','Select matching options','Выбрать найденные','Seleccionar coincidencias'],
['noOptions','No matching options','Ничего не найдено','No hay coincidencias'],
['selectAll','Select all','Выбрать всё','Seleccionar todo'],
['clearGroup','Clear selection','Очистить выбор','Borrar selección'],
['removeFilter','Remove: {name}','Убрать: {name}','Quitar: {name}'],
['studioNavigation','Announcement editor navigation','Навигация редактора объявлений','Navegación del editor de anuncios'],
['editAnnouncement','Edit announcement','Редактировать объявление','Editar anuncio'],
['previewAndSave','Preview & save','Предпросмотр и сохранение','Vista previa y guardar'],
['photoPosition','Photo position','Положение фото','Posición de la foto'],
['photoPositionHelp','Move the photo up or down to keep faces in frame.','Сдвигай фото вверх или вниз, чтобы лица оставались в кадре.','Mueve la foto hacia arriba o abajo para mantener las caras en el encuadre.'],
['homeTitle','Find your swing. Find your people.','Найди свой свинг. Найди своих людей.','Encuentra tu swing. Encuentra tu gente.'],
['homeIntro','Classes, music and good company. A home for Lindy Hop, solo jazz and the swing community.','Занятия, музыка и хорошая компания. Место встречи любителей линди-хопа, соло-джаза и свинга.','Clases, música y buena compañía. Un hogar para el Lindy Hop, el solo jazz y la comunidad swing.'],
['explore','Explore events','Найти события','Explorar eventos'],
['danceWays','Make room for more dancing','Больше места для танцев','Haz espacio para bailar más'],
['regularTitle','A little swing, every week','Немного свинга каждую неделю','Un poco de swing cada semana'],
['regularText','Regular classes. Familiar faces. Your own pace.','Регулярные занятия. Знакомые лица. Твой темп.','Clases regulares. Caras conocidas. A tu ritmo.'],
['soloTitle','Your own groove','Твой собственный грув','Tu propio groove'],
['soloText','Solo jazz, footwork and improvisation. No partner required.','Соло-джаз, работа ног и импровизация. Партнёр не нужен.','Solo jazz, pasos e improvisación. Sin pareja.'],
['partnerTitle','Better together','Вместе ещё интереснее','Mejor en compañía'],
['partnerText','Lindy Hop and the joy of connecting on the dance floor.','Линди-хоп и радость общения на танцполе.','Lindy Hop y la alegría de conectar en la pista.'],
['workshopTitle','Go a little deeper','Погрузись глубже','Profundiza un poco más'],
['workshopText','Workshops, masterclasses and intensives for your next discovery.','Воркшопы, мастер-классы и интенсивы для новых открытий.','Talleres, clases magistrales e intensivos para seguir descubriendo.'],
['socialTitle','See you on the floor','Увидимся на танцполе','Nos vemos en la pista'],
['socialText','Social dancing, live music and a community to come back to.','Вечеринки, живая музыка и сообщество, куда хочется возвращаться.','Bailes sociales, música en vivo y una comunidad a la que volver.'],
['tempoTitle','A place for every tempo','Место для любого темпа','Un lugar para cada tempo'],
['tempoText','Choose your style, level and energy. Combine as many filters as you need.','Выбирай стиль, уровень и нагрузку. В каждом фильтре можно выбрать несколько вариантов.','Elige estilo, nivel e intensidad. Combina tantas opciones como necesites.'],
['beginnerTitle','New to swing? Start here.','Впервые на свинге? Начни здесь.','¿Empiezas con el swing?'],
['beginnerText','Find beginner-friendly classes and check whether you need a partner.','Ищи занятия для начинающих и проверяй, нужно ли приходить с партнёром.','Busca clases para principiantes y comprueba si necesitas llevar pareja.'],
['beginnerCta','Find a first class','Найти первый урок','Encontrar mi primera clase'],
['hostTitle','Bring your community together','Собери своё сообщество','Reúne a tu comunidad'],
['hostText','Create an event or make an announcement people can save and share.','Создай событие или объявление, которое легко сохранить и переслать.','Crea un evento o un anuncio fácil de guardar y compartir.'],
['announcement','Make an announcement','Создать объявление','Crear anuncio'],
['photoSoon','Your community photo will go here','Здесь будет фото сообщества','Aquí irá una foto de la comunidad'],
['studioTitle','Announcement studio','Студия объявлений','Estudio de anuncios'],
['studioIntro','Make an image for Instagram or WhatsApp. Add your own photo and save it in one tap.','Сделай изображение для Instagram или WhatsApp. Добавь своё фото и сохрани в одно нажатие.','Crea una imagen para Instagram o WhatsApp. Añade tu foto y guárdala con un toque.'],
['posterTitle','Headline','Заголовок','Título'],
['posterDate','Date & time (include time zone)','Дата и время (с часовым поясом)','Fecha y hora (incluye zona horaria)'],
['posterPlace','Place','Место','Lugar'],
['posterText','Short message','Короткий текст','Mensaje breve'],
['posterPhoto','Photo (optional)','Фото (необязательно)','Foto (opcional)'],
['photoHelp','JPG, PNG or WebP, up to 10 MB. Your photo stays on this device.','JPG, PNG или WebP до 10 МБ. Фото остаётся на этом устройстве.','JPG, PNG o WebP de hasta 10 MB. Tu foto se queda en este dispositivo.'],
['posterSize','Image size','Размер изображения','Tamaño de imagen'],
['sizePost','Post · 1080 × 1350','Пост · 1080 × 1350','Publicación · 1080 × 1350'],
['sizeStory','Story / status · 1080 × 1920','Сторис / статус · 1080 × 1920','Historia / estado · 1080 × 1920'],
['sizeSquare','Square · 1080 × 1080','Квадрат · 1080 × 1080','Cuadrado · 1080 × 1080'],
['savePng','Save PNG','Сохранить PNG','Guardar PNG'],
['shareImage','Share image','Поделиться изображением','Compartir imagen'],
['copyCaption','Copy caption & link','Скопировать текст и ссылку','Copiar texto y enlace'],
['copied','Caption copied','Текст скопирован','Texto copiado'],
['shareHelp','Choose an app in your device’s share menu, or save the PNG and attach it in Instagram or WhatsApp.','Выбери приложение в меню устройства или сохрани PNG и прикрепи его в Instagram или WhatsApp.','Elige una app en el menú del dispositivo o guarda el PNG y adjúntalo en Instagram o WhatsApp.'],
['shareFallback','Direct sharing is unavailable. Save the PNG and attach it in the app.','Прямая отправка недоступна. Сохрани PNG и прикрепи его в приложении.','No se puede compartir directamente. Guarda el PNG y adjúntalo en la app.'],
['imageError','Could not prepare the image. Try another photo.','Не удалось подготовить изображение. Попробуй другое фото.','No se pudo preparar la imagen. Prueba con otra foto.'],
['removePhoto','Remove photo','Убрать фото','Quitar foto'],
['preview','Preview','Предпросмотр','Vista previa'],
['shareEvent','Share this event','Поделиться событием','Compartir evento'],
['selectedDate','Uses the selected date. Preview your image before sharing.','Используется выбранная дата. Проверь изображение перед отправкой.','Se usa la fecha seleccionada. Revisa la imagen antes de compartir.'],
['sampleTitle','Your next swing night','Твой следующий свинговый вечер','Tu próxima noche de swing'],
['sampleText','An evening of rhythm, music and good company.','Вечер ритма, музыки и хорошей компании.','Una noche de ritmo, música y buena compañía.'],
['photoError','Choose a JPG, PNG or WebP no larger than 10 MB.','Нужен JPG, PNG или WebP размером не больше 10 МБ.','Elige JPG, PNG o WebP de hasta 10 MB.'],
['copyManual','Caption (you can also copy it manually)','Текст (можно скопировать вручную)','Texto (también puedes copiarlo manualmente)'],
['filterHelp','Match any selected option within a group; combine groups to narrow your search.','Внутри группы подходит любой выбранный вариант. Разные группы уточняют поиск вместе.','Coincide con cualquier opción del grupo; combina grupos para precisar la búsqueda.']
];
for(const [index,locale] of ['en','ru','es'].entries()){const file=`apps/web/messages/app/${locale}.json`;const data=JSON.parse(readFileSync(file,'utf8'));for(const row of rows)data[row[0]]=row[index+1];writeFileSync(file,JSON.stringify(data,null,2)+'\n');}
